### ISSUE TITLE
Question on coverage requirements of human variant calling with medaka tutorial

### ISSUE THREAD

**Issue by niuniumama** [epi2me-labs/tutorials#12]
Hi, thanks for developing the tutorials, they are really helpful. 
I am using medaka for human variant calling with PCR amplicons. Would like to ask if medaka could be used for variant calling with 500 to1000 fold coverage analysis. As described in the tutorial, medaka is optimized to work with reference coverage in the range of 30 to100 fold. I am not sure if the result will be affect if the coverage is higher than 100 fold coverage. And if medaka could not be used in such high coverage analysis, do you have any recommend software or pipeline for human variant calling with 500~1000 fold coverage? Thanks

**Comment by sagrudd** [comment]
Hello @niuniumama - I am delighted that you are enjoying the tutorials.

As you have noted Medaka's variant calling is optimised to work with reference coverage in the range of 30-100 fold. This is due to Medaka being designed to work with whole genome sequencing datasets where coverage is expected to be rather low compared to what might be obtained in a targeted sequencing experiment. 

In the tutorial we provide a code cell (and some additional documentation) that may be used to downsample from your 1000X coverage to a more tractable depth for the method. The code block looks much like this

![image](https://user-images.githubusercontent.com/3848500/97413710-03877900-18fb-11eb-8a72-eb5c4a3dac65.png)

Since you are working with amplicon data with a coverage of 500-1000x, it would be simplest to downsample using samtools

```
!samtools view -@ 4 -h -s 0.1 "$output_folder/alignments.bam" | samtools sort - > "$output_folder/alignments_sample.bam"
!mv "$output_folder/alignments_sample.bam"  "$output_folder/alignments.bam"
!samtools index "$output_folder/alignments.bam"
```

* The 1st line above downsamples the created BAM with a proportion of 0.1 (with your data to 50-100X) coverage (adjust -s parameter as required) before sorting the BAM file for subsequent steps
* 2nd line replaces the previous BAM with this new subsampled BAM 
* 3rd line re-indexes the BAM for usage with Medaka in the next step

Good luck - let us know how this works for you!

**Comment by niuniumama** [comment]
Hi @sagrudd thanks for kindly reply. 
Analysis the variants at >500X coverage is necessary for my data, since sometimes I need to explore the variants with relative low ratio. I have tried this tutorial with 1000X, 500X, 200X and 50X,  downsample to 50-200X sometimes result in missing SNPs in my case. As you explained, medaka is designed to work with WGS data and optimized to work with 30-100X coverage, I would like to ask if medaka could be used for variant calling at >500x coverage.

**Comment by cjw85** [comment]
Medaka has not been designed with the idea of low frequency alleles in mind. The premise of its approach is that you have a strictly diploid sample with a 50:50 allele ratio.

For your experiment I would recommend our newly released UMI amplicon protocol and associated analysis workflow: https://github.com/nanoporetech/pipeline-umi-amplicon. With the consensus sequence from multiple UMI tagged reads you will be able to identify the low frequency alleles.
